(function(){'use strict';var e=function(a,c,b){a=parseInt(a.getAttribute(c),10);isNaN(a)&&(a=b);return a};var h=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},k=function(a){if(h(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&h(a))return a;return null};var n=/[^\d]+$/,p=function(a,c,b){if(!a.hasAttribute(c))return 0;c=a.getAttribute(c);if(isNaN(parseFloat(c)))b=0;else{a=parseFloat(c);(c=(c=c.match(n))&&c[0]||null)&&(c=c.trim());var d=a;"%"==c&&(d=Number((a/100*b).toFixed(2)));b=d}return b};var q=function(a,c){var b=document.createEvent("Event");b.initEvent(a,!0,!0);c.dispatchEvent(b)};var r=function(){};goog.inherits(r,HTMLElement);r.prototype.createdCallback=function(){this.canvas=null;this.i=!1;this.a=[];this.s=this.I.bind(this);this.H=this.J.bind(this);this.g=this.K.bind(this);this.l=[];this.w=this.C.bind(this);this.b=null;this.h=2;this.m=null;this.v=-1;this.u=null};
r.prototype.attachedCallback=function(){this.o=this.clientWidth;this.j=this.clientHeight;this.f=window.devicePixelRatio;this.canvas||(this.canvas=this.ownerDocument.createElement("canvas"),this.canvas.style.width=this.o+"px",this.canvas.style.height=this.j+"px",this.canvas.width=this.o*this.f,this.canvas.height=this.j*this.f,this.appendChild(this.canvas));this.c=this.canvas.getContext("2d");this.G=this.hasAttribute("autoplay");var a=parseFloat(this.getAttribute("time-limit"));isFinite(a)||(a="-1");
this.v=1E3*(0<a?a:-1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var c=(a=k(this))&&"function"==typeof a.gwdIsLoaded;(!a||c&&a.gwdIsLoaded())&&this.gwdLoad()}};r.prototype.detachedCallback=function(){t(this);this.stop()};
r.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){t(this);for(var a=0,c=0;c<this.children.length;c++){var b=this.children[c];if(u(b)&&(!b.gwdIsLoaded||!b.gwdIsLoaded()))w(this,b),this.addEventListener("request-reload",this.H,!1);else if("image"==b.getAttribute("assettype")){var d=b.getAttribute("source"),f=p(b,"left",this.o),g=p(b,"top",this.j),l=p(b,"width",this.o),m=p(b,"height",this.j),v=e(b,"opacity",100);d={canvas:null,src:d,B:f*this.f,D:g*this.f,F:l*this.f,A:m*this.f,opacity:Math.min((0<=
v?v:100)/100,1)};f=this.ownerDocument.createElement("img");this.a.push(f);f.addEventListener("load",this.g,!1);f.addEventListener("error",this.g,!1);this.l[a]=d;b.setAttribute("image-index",a);f.setAttribute("image-index",a++);f.width=d.F;f.height=d.A;f.src=d.src}}this.i=!0;x(this)}};r.prototype.gwdIsLoaded=function(){return this.i&&0==this.a.length};
var w=function(a,c){-1==a.a.indexOf(c)&&(a.a.push(c),c.addEventListener("ready",a.s,!1));c.gwdLoad&&c.gwdLoad()},t=function(a){for(;a.a.length;){var c=a.a.pop();c.removeEventListener("ready",a.s,!1);c.removeEventListener("load",a.g,!1);c.removeEventListener("error",a.g,!1)}a.i=!1;a.l.length=0},x=function(a){a.i&&0==a.a.length&&(q("ready",a),a.G?a.play(!0):null!=a.m&&a.play(a.m),a.m=null)};
r.prototype.I=function(a){a=a.target;var c=this.a.indexOf(a);0<=c&&(this.a.splice(c,1),a.removeEventListener("ready",this.s,!1),x(this))};r.prototype.J=function(a){w(this,a.target)};
r.prototype.K=function(a){var c=this,b=a.target;b.removeEventListener("load",this.g,!1);b.removeEventListener("error",this.g,!1);var d=this.a.indexOf(b);if(0<=d){var f=parseInt(b.getAttribute("image-index"),10);if("load"==a.type){var g=this.ownerDocument.createElement("canvas");g.width=b.width;g.height=b.height;var l=this.l[f],m=g.getContext("2d");m.globalAlpha=l.opacity;setTimeout(function(){d=c.a.indexOf(b);c.a.splice(d,1);m.drawImage(b,0,0,b.width,b.height);l.canvas=g;x(c)},50)}else this.a.splice(d,
1),x(this)}};var u=function(a){return"gwd-particles"==a.tagName.toLowerCase()};r.prototype.play=function(a){if(!this.gwdIsLoaded())this.m=0!=a;else if(0!=this.h){null==this.u&&(this.u=Date.now());if(2==this.h)for(var c=0;c<this.children.length;c++){var b=this.children[c].hasAttribute("autoplay");u(this.children[c])&&b&&this.children[c].play()}0==a?this.C(!1):this.b=requestAnimationFrame(this.w);this.h=0}};r.prototype.pause=function(){this.b&&(cancelAnimationFrame(this.b),this.b=null);this.h=1};
r.prototype.stop=function(){if(2!=this.h){for(var a=0;a<this.children.length;a++)u(this.children[a])&&this.children[a].stop();this.b&&(cancelAnimationFrame(this.b),this.b=null);this.h=2;this.c.clearRect(0,0,this.canvas.width,this.canvas.height)}};
r.prototype.C=function(a){if(0!=a&&0<this.v&&Date.now()-this.u>this.v)this.pause(),q("timelimitreached",this);else{this.c.clearRect(0,0,this.canvas.width,this.canvas.height);for(var c=0;c<this.children.length;c++){var b=this.children[c];b.hasAttribute("hidden")||(u(b)&&b.gwdIsLoaded()?b.updateAndDraw():"image"==b.getAttribute("assettype")&&(b=e(b,"image-index",-1),-1!=b&&(b=this.l[b],b.canvas?this.c.drawImage(b.canvas,b.B,b.D):this.hasAttribute("data-gwd-node")&&(this.c.strokeStyle="#c0c0c0",this.c.lineWidth=
1,this.c.strokeRect(b.B,b.D,b.F,b.A)))))}0!=a&&(this.b=requestAnimationFrame(this.w))}};document.registerElement("gwd-particleeffects",{prototype:r.prototype});}).call(this);
